# File generated by cdo from CONTRIBUTING.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Run relevant tasks'
	@echo '  build    Build custom k6 with extension'
	@echo '  clean    Clean the working directory'
	@echo '  doc      Updating the documentation'
	@echo '  format   Format the go source codes'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  security Run security checks'
	@echo '  snapshot Creating an executable binary with a snapshot version'
	@echo '  test     Run the tests'

# Run relevant tasks
.PHONY: all
all: clean format lint security test build makefile

# Build custom k6 with extension
.PHONY: build
build: 
	@(\
		xk6 build --with github.com/szkiba/xk6-top=.;\
	)

# Clean the working directory
.PHONY: clean
clean: 
	@(\
		rm -rf ./k6 ./coverage.txt ./build ./node_modules ./bun.lockb;\
	)

# Updating the documentation
.PHONY: doc
doc: 

# Format the go source codes
.PHONY: format
format: 
	@(\
		go fmt ./...;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		golangci-lint run ./...;\
		xk6 lint;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Run security checks
.PHONY: security
security: 
	@(\
		gosec -quiet ./...;\
		govulncheck ./...;\
	)

# Creating an executable binary with a snapshot version
.PHONY: snapshot
snapshot: 
	@(\
		goreleaser build --snapshot --clean --single-target -o build/k6top;\
	)

# Run the tests
.PHONY: test
test: 
	@(\
		go test -count 1 -race -coverprofile=coverage.txt -timeout 60s ./...;\
	)

