Set Padding 4
Set Margin 0
Set FontSize 14
Set Width 754
Set Height 594
Set FontFamily "Monospace"

Output build/readme.gif
Set Theme "GitHub Dark"

Hide
Type "asciinema rec -c 'go run ./cmd/k6top' --overwrite build/readme.cast"
Enter
Sleep 1s
Show

# Overview
Sleep 5s
Right
# Trend
Sleep 1s
Right
# Counter
Sleep 1s
Right
# Rate
Sleep 1s
Right
# Gauge
Sleep 1s
Right
# HTTP
Sleep 1s
Right
# gRPC
Sleep 1s
Right
# WS
Sleep 1s
Right
# Browser
Sleep 1s
Right
# Help
Sleep 1s

Hide
Ctrl+D

