name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - README.md
      - "releases/**"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: go test ./...
